<?php
$apikey = "rzp_test_A2J7BouQU4XB3F";
$name = $_POST['name'];
$email = $_POST['email'];
$phone = $_POST['phone'];
$checkin_date = $_POST['checkin_date'];
$checkout_date = $_POST['checkout_date'];
$checkindifference = $_POST['checkindifference'];
$booking_type = $_POST['booking_type'];
$num_guests = $_POST['num_guests'];
$oid = $_POST['oid'];
$total = $_POST['total'];



?>



<script src="https://code.jquery.com/jquery-3.5.0.min.js"></script>

<form action="https://www.example.com/payment/success/" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey;?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $total * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo 'OID'.rand(100,1000).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay"
    data-name="PSYNET"
    data-description="A World beyond imagination"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="<?php echo $name;?>"
    data-prefill.email="<?php echo $email;?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>